name: Frontend CD - Deploy frontend to AKS

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'k8s/frontend/**'
      - '.github/workflows/frontend_cd.yml'

env:
  ACR_LOGIN_SERVER: ${{ secrets.ACR_LOGIN_SERVER }}
  IMAGE_TAG: ${{ github.sha }}

jobs:
  deploy_frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure login (Service Principal JSON)
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup kubectl
        uses: tale/kubectl-action@v1
        with:
          base64-kube-config: ${{ secrets.KUBE_CONFIG }}
          kubectl-version: v1.32.0

      # apply front-end manifests
      - name: Apply frontend manifests
        run: |
          if [ -d k8s/frontend ]; then
            kubectl apply -f k8s/frontend
          else
            kubectl apply -f k8s
          fi

      # ensure deployment uses fresh image
      - name: Update image to latest SHA (idempotent)
        run: |
          kubectl set image deployment/frontend \
            frontend=${ACR_LOGIN_SERVER}/frontend:${IMAGE_TAG} --record || true

      - name: Wait for rollout
        run: kubectl rollout status deployment/frontend --timeout=120s || true

      - name: Show services
        run: kubectl get deploy,po,svc -o wide
