name: Frontend CI - Build and Push Image to ACR

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend_ci.yml'

env:
  ACR_LOGIN_SERVER: ${{ secrets.ACR_LOGIN_SERVER }}
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build_and_push_frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure login (Service Principal JSON)
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Derive ACR_NAME for CLI login
        run: echo "ACR_NAME=${ACR_LOGIN_SERVER%%.azurecr.io}" >> $GITHUB_ENV

      - name: Login to ACR
        run: az acr login --name "$ACR_NAME"

      - name: Build & Push frontend
        run: |
          docker build -t $ACR_LOGIN_SERVER/frontend:${IMAGE_TAG} ./frontend
          docker push $ACR_LOGIN_SERVER/frontend:${IMAGE_TAG}
          docker tag  $ACR_LOGIN_SERVER/frontend:${IMAGE_TAG} $ACR_LOGIN_SERVER/frontend:latest
          docker push $ACR_LOGIN_SERVER/frontend:latest

      - name: Logout
        if: always()
        run: az logout
