name: Release (Main) – Build & Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-test:
    name: PyTest (${{ matrix.service }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - backend/product_service
          - backend/order_service
    defaults:
      run:
        working-directory: ${{ matrix.service }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Run tests
        run: pytest -q

  deploy:
    name: Deploy (gated by tests)
    runs-on: ubuntu-latest
    needs: [ build-and-test ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # ↓ Replace with your real deploy (AKS, ACR, Static Web Apps, etc.)
      - name: Simulated deploy
        run: |
          echo "Deploying only after tests pass on main..."
          # ./scripts/deploy.sh
